doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: false
# config/packages/doctrine_migrations.yaml
    storage:
        table_storage:
            table_name: doctrine_migration_versions_rm
